### ISSUE TITLE
Runtime error during training

### ISSUE THREAD

**Issue by GiYeolKim** [mustansarfiaz/DDAM-PS#2]
Hi, I am facing some error while running your codes.

<img width="947" alt="KakaoTalk_20240511_154310278" src="https://github.com/mustansarfiaz/DDAM-PS/assets/93780518/681a1483-06ea-4ef9-931f-d211fe83fa73">

Could you give some help?

**Comment by mustansarfiaz** [comment]
Hi,

seems like you modified the resnet.py file. I suggest, first running the code without modifying anything. The error is at line #66, but the github repo is returning out at line #66. 
Moreover, Im using identity at line 63, however you are using identity[0]. Please check this.


Regards

**Comment by GiYeolKim** [comment]
Thank you for your response.
I took this screenshot while trying to fix the error, and running your original code without any modifications also results in the same error.

When I run the code without any modifications, I encounter an error that says 
"forward() takes 3 positional arguments but 4 were given." 
Can you check this?
![image](https://github.com/mustansarfiaz/DDAM-PS/assets/93780518/5330bef9-846c-4edb-9e48-1b375c69ac9c)

The code does run if I don't pass is_intermite as an argument in line 64 of resnet.py, but is that where the problem is?

**Comment by GiYeolKim** [comment]
Additionally, I have another question. 
It seems that NVIDIA Apex is not being installed properly. 
Could you help me with how to install Apex when running the model?

**Comment by zengyingzhu1** [comment]
> 另外，我还有一个问题。 NVIDIA Apex 似乎没有正确安装。 您能帮我了解如何在运行模型时安装 Apex 吗？
can u tell me?where is epoch_10.pth?

**Comment by mustansarfiaz** [comment]
@GiYeolKim 

Unfortunately, I don't remember exactly. However, I asked my co-lead author. He knows better and can help you but currently, he is busy this week. 

It seems like that APEX is not installed correctly. Could you confirm it and try to install it via
`
https://github.com/NVIDIA/apex
`
Regards
Mustansar

**Comment by mustansarfiaz** [comment]
There is no update.
