### ISSUE TITLE
Hi, I am facing some error while running your codes.

### ISSUE THREAD

**Issue by zengyingzhu1** [mustansarfiaz/DDAM-PS#3]
FileNotFoundError: [Errno 2] No such file or directory: './output/SeqNet-DA4/exp/prw_da/epoch_10.pth'
where is it

**Comment by mustansarfiaz** [comment]
Hi
You need a checkpoint when you want to do the inference. You need to download the pretrained checkpoints and point the path in the script. For example, in this line, $MODEL_PATHis is the checkpoint path.

`python train_da_dy_cluster.py --cfg configs/cuhk_sysu_da.yaml --eval --ckpt $MODEL_PATH`

During the training, you need to run the line as:
`
python train_da_dy_cluster.py --cfg configs/cuhk_sysu_da.yaml

`

Moreover, set your cuhk_sysu_da.yaml file for dataset paths.

Regards
Mustansar

**Comment by zengyingzhu1** [comment]
HI。Hello, excuse me. Since I want to do the inference.  I ran the file as you asked. D:\Anaconda3\envs\DDAM\python.exe D:\Data\DDAM-PS-main\train_da_dy_cluster.py --cfg configs/cuhk_sysu_da.yaml --eval --ckpt pth/target_prw.pth 
Then the following appears，I would like to ask if the following appears to indicate a test evaluation? Because it looks very much like a training phase to me.

source dataset:  CUHK-SYSU
target dataset:  PRW
Creating model and convert dsbn
convert_dsbn 2D
bn1
convert_dsbn 2D
bn2
convert_dsbn 2D
bn3
convert_dsbn 2D
1
convert_dsbn 2D
bn1
convert_dsbn 2D
bn2
convert_dsbn 2D
bn3
convert_dsbn 2D
bn1
convert_dsbn 2D
bn2
convert_dsbn 2D
bn3
Building dataset
=> CUHK-SYSU-train loaded:
|  dataset  |  split  |  num_images  |  num_boxes  |  num_labeled_pids  |  min_labeled_pid  |  max_labeled_pid  |  unlabeled_pid  |
|:---------:|:-------:|:------------:|:-----------:|:------------------:|:-----------------:|:-----------------:|:---------------:|
| CUHK-SYSU |  train  |    11206     |    55272    |        5532        |         1         |       5532        |      5555       |
source_classes :5533
Loading test data
=> PRW-gallery loaded:
|  dataset  |  split  |  num_images  |  num_boxes  |  num_labeled_pids  |  min_labeled_pid  |  max_labeled_pid  |  unlabeled_pid  |
|:---------:|:-------:|:------------:|:-----------:|:------------------:|:-----------------:|:-----------------:|:---------------:|
|    PRW    | gallery |     6112     |    25062    |        544         |         1         |        933        |      5555       |
=> PRW-query loaded:
|  dataset  |  split  |  num_images  |  num_boxes  |  num_labeled_pids  |  min_labeled_pid  |  max_labeled_pid  |
|:---------:|:-------:|:------------:|:-----------:|:------------------:|:-----------------:|:-----------------:|
|    PRW    |  query  |     2057     |    2057     |        450         |        479        |        933        |
loaded checkpoint pth/target_prw.pth
model was trained for 19 epochs
=> PRW-train loaded:
|  dataset  |  split  |  num_images  |  num_boxes  |  num_labeled_pids  |  min_labeled_pid  |  max_labeled_pid  |  unlabeled_pid  |
|:---------:|:-------:|:------------:|:-----------:|:------------------:|:-----------------:|:-----------------:|:---------------:|
|    PRW    |  train  |     5704     |    18048    |        483         |         1         |        483        |      5555       |
100% 6112/6112 [18:14<00:00,  5.58it/s]
100% 2057/2057 [06:16<00:00,  5.46it/s]
100% 2057/2057 [01:43<00:00, 19.84it/s]
all detection:
  recall = 84.84%
  ap = 81.47%
search ranking:
  mAP = 35.78%
  top- 1 = 80.75%
  top- 5 = 88.33%
  top-10 = 90.62%

**Comment by mustansarfiaz** [comment]
Hi,

yes, the evaluation appears like that. Can you confirm for me that these numbers are based on your trained model?
I'm asking because mine are slightly higher than what these are showing. I'm asking because I re-run the code multiple times to get the same numbers as in the paper before uploading the code on Git Hub.

Or it could be possible of different library variants.

Regards

**Comment by zengyingzhu1** [comment]
HI
I used the model weights file downloaded from the link provided in your form to evaluate the results.
regard

**Comment by zengyingzhu1** [comment]
HI
Hello, I have been able to run through your assessment. However, there are some issues with the training process that prevent it from running, can you help me with that? The reported errors are as follows:Traceback (most recent call last):
  File "D:\Data\DDAM-PS-main\train_da_dy_cluster.py", line 324, in <module>
    main(args)
  File "D:\Data\DDAM-PS-main\train_da_dy_cluster.py", line 276, in main
    train_one_epoch_da(cfg, model, optimizer, train_loader_s, train_loader_t, device, epoch, tfboard)
  File "D:\Data\DDAM-PS-main\engine.py", line 94, in train_one_epoch_da
    loss_dict = model(images1, targets1, images2, targets2, epoch = epoch)
  File "D:\Anaconda3\envs\DDAM\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Data\DDAM-PS-main\models\seqnet_da.py", line 153, in forward
    da_ins_feas_s, da_ins_labels_s, da_ins_feas_s_before, da_ins_labels_s_before = self.roi_heads.extract_da(features_s, proposals_s, images_s.image_sizes, targets_s)
  File "D:\Data\DDAM-PS-main\models\roi_head_da.py", line 138, in extract_da
    proposal_features = self.box_head(proposal_features)
  File "D:\Anaconda3\envs\DDAM\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Data\DDAM-PS-main\models\resnet.py", line 84, in forward
    feat = super(Res5Head, self).forward(x)
  File "D:\Anaconda3\envs\DDAM\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "D:\Anaconda3\envs\DDAM\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconda3\envs\DDAM\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "D:\Anaconda3\envs\DDAM\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconda3\envs\DDAM\lib\site-packages\torchvision\models\resnet.py", line 144, in forward
    out = self.conv1(x)
  File "D:\Anaconda3\envs\DDAM\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconda3\envs\DDAM\lib\site-packages\torch\nn\modules\conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\Anaconda3\envs\DDAM\lib\site-packages\torch\nn\modules\conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "D:\Anaconda3\envs\DDAM\lib\site-packages\apex\amp\wrap.py", line 21, in wrapper
    args[i] = utils.cached_cast(cast_fn, args[i], handle.cache)
  File "D:\Anaconda3\envs\DDAM\lib\site-packages\apex\amp\utils.py", line 97, in cached_cast
    if cached_x.grad_fn.next_functions[1][0].variable is not x:
IndexError: tuple index out of range

**Comment by mustansarfiaz** [comment]
Hi

It means you are using different versions of libraries.

About the error, seems like there are installation/configuration issues with your apex. Can you check the size of x at 
`File "D:\Data\DDAM-PS-main\models\resnet.py", line 84, in forward
feat = super(Res5Head, self).forward(x)`
The main code is fine but looks like apex has some issues in your environment.

Regards

**Comment by zengyingzhu1** [comment]
HI
Maybe I have some problems with my apex installation, can you tell me the version of python you are using, the cuda version? I'm using python 3.8 and when I install apex he shows successful installation and when I type in pip list it does have the library apex in it, but once I do the training he shows ModuleNotFoundError: No module named 'amp_C '. I don't know why. Searching online doesn't give me any solution either. Right now the code just won't run for training.
regards！

**Comment by mustansarfiaz** [comment]
Hi

I have changed my machine and could not find which Cuda version we used for Apex.

Regards

**Comment by mustansarfiaz** [comment]
There is no update
